// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FieldType interface {
	IsFieldType()
}

type BoolType struct {
	BoolValue bool `json:"boolValue"`
}

func (BoolType) IsFieldType() {}

type FloatType struct {
	FloatValue float64 `json:"floatValue"`
}

func (FloatType) IsFieldType() {}

type IntegerType struct {
	IntegerValue int `json:"integerValue"`
}

func (IntegerType) IsFieldType() {}

type Signal struct {
	ID        int         `json:"id"`
	Timestamp string      `json:"timestamp"`
	Name      string      `json:"name"`
	Vars      []*Variable `json:"vars"`
}

type StringType struct {
	StringValue string `json:"stringValue"`
}

func (StringType) IsFieldType() {}

type Variable struct {
	ID    int       `json:"id"`
	Value FieldType `json:"value"`
}
